import {Color} from '../Utils/Color';
import {screenDiagonal} from '../Utils/helperFunctions';
export const SPACING = 10;

const {StyleSheet, Dimensions} = require('react-native');
const {width, height} = Dimensions.get('window');
const dgl = screenDiagonal();

const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: '#F7F6F8',
    justifyContent: 'center',
    padding: SPACING * 2,
  },
  ContainerF1: {
    flex: 1,
  },
  InputContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginVertical: 20,
    marginHorizontal: 10,
  },
  searchSection: {
    flex: 1,
    width: dgl * 0.03,
    borderColor: 'gray',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 5,
    marginHorizontal: 5,
  },
  aligncenter: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  subscriptionAd: {
    flex: 4,
    backgroundColor: Color.shadedViolet,
    marginHorizontal: dgl * 0.02,
    marginVertical: dgl * 0.05,
    alignItems: 'center',
    borderRadius: 10,
    flexDirection: 'column',
  },
  CWidth: {width: '100%', padding: SPACING * 2},
  CRow: {flex: 1, flexDirection: 'row'},
  Cmargin: {margin: 20},
  Cpadding: {padding: SPACING},
  titleText: {
    fontSize: 15,
    padding: SPACING,
    marginLeft: SPACING,
    color: Color.grey,
    fontFamily: 'SFProDisplay-Regular',
  },
  dateText: {
    fontSize: 15,
    fontWeight: '200',
    color: Color.white,
    paddingVertical: SPACING,
  },
  reportHeaderText: {fontSize: 16, fontWeight: '600'},
  nameText: {fontSize: 20, fontWeight: '500', color: Color.white},
  ReportHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: Color.primaryBlue,
    textAlign: 'center',
    width: width,
    padding: 20,
  },
  padded: {
    padding: SPACING,
  },
  manageIntrest: {
    width: width,
    marginTop: 20,
  },
  compatibilityView: {
    alignItems: 'center',
    padding: SPACING,
  },
  compatibilityText: {
    fontSize: 20,
    marginBottom: dgl * 0.005,
    color: Color.white,
    fontWeight: '700',
    fontFamily: 'SFProDisplay-Regular',
  },

  compatibilitySubText: {
    fontSize: 15,
    marginBottom: dgl * 0.005,
    color: Color.white,
    fontWeight: '400',
    fontFamily: 'SFProDisplay-Regular',
  },
  focusView: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    width: dgl * 0.35,
  },
  loadingView1: {width: width, height: height + 30, position: 'absolute'},
  ErrorView1: {
    flex: 1,
    width: dgl * 0.3,
    height: height,
  },
  ErrorText: {
    fontSize: 20,
    color: Color.black,
    textAlign: 'center',
    fontWeight: '600',
    fontFamily: 'SFProDisplay-Bold',
  },
  ErrorSubText: {
    fontSize: 20,
    color: Color.black,
    textAlign: 'center',
    marginTop: 10,
    fontFamily: 'SFProDisplay-Regular',
  },
  wentWrongText: {
    fontSize: 20,
    width: dgl * 0.34,
    color: Color.black,
    textAlign: 'center',
    marginTop: 10,
    fontFamily: 'SFProDisplay-Regular',
  },
  loadingText: {fontSize: 20, color: Color.white},
  titleText2: {fontSize: 18, paddingLeft: SPACING},
  loading: {
    position: 'absolute',
    bottom: 0,
    marginBottom: 50,
  },
  ErrorTextView: {
    flex: 1,
    bottom: 0,
    marginBottom: 50,
  },
  SubTitileTextNotifications: {
    fontSize: dgl * 0.015,
  },
  SubTitileDark: {
    fontSize: dgl * 0.016,
    marginTop: SPACING,
    color: Color.black,
  },
  alignItemStyle: {alignItems: 'center'},
  svgCenter: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  ReportDetailsDesc: {flex: 1, padding: 20, marginTop: 20},
  header: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  justifyView: {justifyContent: 'space-between'},
  logo: {
    width: 30,
    height: 30,
    marginRight: SPACING,
  },
  homeView3: {alignItems: 'flex-start', padding: SPACING},
  //SignUpScreen
  Button: {
    borderRadius: 25,
    padding: SPACING,
    margin: 15,
    elevation: 0.5,
    shadowColor: 'grey',
    shadowOpacity: 0.5,
    shadowOffset: {width: -2, height: 4},
  },
  homeheading: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Color.white,
    fontFamily: 'SFProDisplay-Regular',
    padding: SPACING,
  },
  homeView2: {flex: 1},
  smallText: {
    fontSize: 12,
    textAlign: 'center',
    padding: 22,
    fontFamily: 'SFProDisplay-Regular',
  },
  SkipText: {margin: 20, color: 'grey'},

  BottomSvgStyle: {bottom: 0, position: 'absolute', alignSelf: 'center'},
  buttonTextStyle: {textAlign: 'center', fontSize: 20},
  LinkText: {color: 'blue', textDecorationLine: 'underline'},
  EditText: {color: 'blue', fontSize: 16},
  TopRightSvgStyle: {position: 'absolute', top: 0, left: 90},
  TopRightSvgStyle2: {position: 'absolute', top: 0, left: SPACING},
  StandartText: {fontSize: 30},
  weighted: {fontWeight: 'bold'},
  IconMargin: {marginHorizontal: 25, top: 4},
  signUpMethView: {
    flex: 1.5,
    justifyContent: 'space-evenly',
  },
  signUpMethView2: {
    flex: 1,
    margin: SPACING * 2,
    justifyContent: 'flex-end',
  },
  signUpMethBottomView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    width: '90%',
    backgroundColor: Color.white,
    marginLeft: 15,
    alignItems: 'center',
    padding: 15,
    borderRadius: 12,
    shadowColor: 'grey',
    shadowOpacity: 0.3,
    shadowOffset: {width: -2, height: 4},
  },
  DateTimeInput: {
    height: 40,
    textAlign: 'left',
  },
  paginationView: {
    position: 'absolute',
    bottom: SPACING * 2,
    width: width,
    padding: SPACING * 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  input2: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    paddingHorizontal: SPACING,
    borderRadius: 5,
  },
  input3: {
    height: 40,

    color: Color.grey,
    borderColor: 'gray',
    borderBottomWidth: StyleSheet.hairlineWidth,

    borderRadius: 5,
    margin: 10,
  },
  Editinput3: {
    height: 40,

    color: Color.grey,
    borderColor: 'gray',
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: SPACING,

    backgroundColor: Color.shadedWhite,
    margin: 10,
  },
  NumSignUpThemeStylle: {
    position: 'absolute',
    top: 0,
    alignSelf: 'center',
    alignItems: 'center',
  },

  //Custom
  LinearBotton: {
    borderRadius: 20,
    margin: SPACING * 2,
    padding: SPACING,
    alignSelf: 'center',
  },
  TextWhite: {
    textAlign: 'center',
    color: Color.shadedWhite,
    fontSize: 18,
  },
  TextWhiteS12: {
    textAlign: 'center',
    color: Color.shadedWhite,
    fontSize: 12,
  },
  TextWhiteS10: {
    textAlign: 'center',
    color: Color.shadedWhite,
    fontSize: 10,
  },
  viewToRender: {
    position: 'absolute',
    bottom: 0,
    width: width,
    height: height / 3.5,
  },
  //Home
  text1: {fontSize: 20, marginLeft: 30},
  Desctext: {color: Color.white, fontSize: dgl * 0.015},
  textBold: {fontSize: 20, fontWeight: 'bold'},
  textSemiBold: {fontSize: 15, fontWeight: 'bold', marginLeft: SPACING},
  width: width / 2,
  SemiBoldText1: {
    fontSize: 15,
    fontWeight: 'bold',
    color: Color.shadedWhite,
    width: width / 3,
  },
  SemiBoldTextfw: {
    fontSize: 15,
    fontWeight: 'bold',
    color: Color.shadedWhite,
    width: width,
  },
  normalText1: {
    fontSize: 15,
    fontFamily: 'SFProDisplay-Regular',
    color: Color.shadedWhite,
  },
  traitsText: {
    marginBottom: 10,
    fontSize: 14,
    color: Color.shadedWhite,
    fontFamily: 'SFProDisplay-Regular',
  },
  TabTextView: {
    marginTop: 20,
    flexDirection: 'row',
    width: width / 2,
    justifyContent: 'space-between',
  },
  imageBgView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: height,
  },
  PackageBG: {
    alignItems: 'center',
    justifyContent: 'center',
    width: dgl * 0.45,
    height: 470,

    top: 0,
  },

  CustomimageBgView: {
    width: width,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    position: 'absolute',
  },
  imageBgViewCustom: {
    flex: 1,
    width: width,
    alignItems: 'center',
    justifyContent: 'center',
    right: 1,
  },
  filterStyle: {
    backgroundColor: '#CDA3EF',
    paddingHorizontal: 30,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#BF7AF3',
    flexDirection: 'row',
    alignItems: 'center',
    width: dgl * 0.13,
    justifyContent: 'space-between',
  },
  LinearView: {
    width: '90%',
    height: 300,
    marginTop: dgl * 0.14,
    borderRadius: 20,
    padding: 20,
  },
  ReportView: {
    width: '90%',
    height: 300,
    marginTop: dgl * 0.14,
    borderRadius: 20,
    padding: 20,
  },
  SvgView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  BoxView2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING,
  },
  BoxView: {
    flex: 1,
    padding: SPACING,
    margin: SPACING,
    borderRadius: SPACING,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Color.white,
    shadowColor: Color.grey,
    shadowOpacity: 0.5,
    shadowOffset: {width: -2, height: 4},
  },
  alignView: {alignItems: 'center'},
  textMargin: {marginTop: SPACING, color: Color.white},
  textMarginBlack: {marginTop: SPACING, color: Color.black},
  LinearLineAlign: {flexDirection: 'row', justifyContent: 'space-between'},
  reportAlign: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width,
  },

  //onBoarding
  cardSpace: {
    width: width,
    height: height / 3,
    padding: SPACING,
    margin: 5,
    borderRadius: 15,
  },
  signupButton: {
    width: dgl * 0.35,
    height: 45,
    alignSelf: 'center',
  },
  welcomeContainer: {
    alignItems: 'flex-start',
    padding: SPACING,
    marginLeft: SPACING * 2,
  },
  //footer
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: 70,
    backgroundColor: Color.darkViolet,
  },
  footerButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 12,
    color: Color.regularViolet,
  },
  ItemListView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: SPACING * 2,
    backgroundColor: Color.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBlockColor: Color.grey,
  },
  // dateTimePicker
  welcomeView: {
    alignSelf: 'flex-start',
    marginLeft: SPACING * 3,
  },
  welcomeTitleText: {fontSize: 25, fontWeight: 'bold'},
  welcomeTextSub: {
    fontSize: 20,
    textAlign: 'left',
    fontWeight: 'bold',
  },

  // Notifications
  MainBoxNotifications: {
    flexDirection: 'row',
    backgroundColor: Color.whiteOpacity,
    justifyContent: 'space-between',
    borderRadius: SPACING,
    width: width - 30,
    marginBottom: SPACING,
  },
  notificationsIndication: {
    width: dgl * 0.01,
    height: dgl * 0.01,
    backgroundColor: Color.regularViolet,
    paddingLeft: SPACING,
    alignSelf: 'center',
    borderRadius: 20,
    marginLeft: SPACING,
  },
  headerNotifyBar: {
    position: 'absolute',
    height: dgl * 0.02,
    width: dgl * 0.02,
    left: 9,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: Color.regularViolet,
  },
  ColoumBoxNotification: {
    padding: SPACING,
    width: width - 50,
    flexDirection: 'column',
  },
  rowBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowBoxHeadline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: Color.white,
    borderBottomWidth: 1,
    padding: 10,
  },

  zodiacBox: {
    height: dgl * 0.1,
    width: dgl * 0.1,
    padding: dgl * 0.03,
    marginHorizontal: width / 3,
    backgroundColor: Color.whiteOpacity,
    justifyContent: 'center',
    borderRadius: dgl * 0.009,
    alignItems: 'center',
  },
  customInput: {
    width: '70%',
    height: 45,
    backgroundColor: '#fff',
    margin: 5,
    padding: 15,
    borderRadius: 12,
    shadowColor: 'grey',
    shadowOpacity: 0.3,
    shadowOffset: {width: -2, height: 4},
  },
  flagContainer: {
    width: 100,
    height: 45,
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: 'grey',
    shadowOpacity: 0.3,
    shadowOffset: {width: -2, height: 4},
  },
  safeArea: {
    flex: 2.6,
    marginTop: 80,
    justifyContent: 'space-around',
  },
  compatibilityContainer: {
    height: dgl * 0.09,
    width: dgl * 0.09,
    justifyContent: 'center',
    borderRadius: dgl * 0.009,
    shadowColor: 'grey',
    shadowOpacity: 0.5,
    shadowOffset: {width: -2, height: 4},
  },
  zodiaImageView: {
    width: dgl * 0.06,
    height: dgl * 0.06,
    alignSelf: 'center',
  },
  zodiaImageView2: {width: dgl * 0.07, height: dgl * 0.07},
  zodiaActive: {
    backgroundColor: '#6F4ED0',
    paddingHorizontal: 8,
    borderRadius: 10,
    marginBottom: 5,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: Color.shadedWhite,
    alignSelf: 'center',
  },
  flatListView1: {
    height: dgl * 0.1,
    width: dgl * 0.1,
    padding: dgl * 0.03,
    marginHorizontal: width / 3,
    backgroundColor: Color.whiteOpacity,
    justifyContent: 'center',
    borderRadius: dgl * 0.009,
    alignItems: 'center',
  },
  zodiaNormal: {
    height: dgl * 0.09,
    width: dgl * 0.09,
    justifyContent: 'center',
    borderRadius: dgl * 0.009,
  },
  arrowStyle: {
    position: 'absolute',
    flexDirection: 'row',
    width: width,
    justifyContent: 'space-between',
    paddingHorizontal: dgl * 0.08,
    alignItems: 'center',
    marginLeft: dgl * 0.02,
    top: dgl * 0.25,
  },
  compatibilityButon: {
    padding: dgl * 0.02,
    backgroundColor: Color.white,
    borderRadius: dgl * 0.05,
  },
  svgBox: {flex: 1, flexDirection: 'row'},
  filterTextStyle: {color: '#fff', width: dgl * 0.06},
  IntrestBox: {
    width: dgl * 0.15,
    height: dgl * 0.15,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2F2F2',
    borderWidth: dgl * 0.002,
    borderColor: '#FFFFFF',
    margin: 20,
    shadowColor: Color.grey,
    shadowOpacity: 0.5,
    shadowOffset: {width: -2, height: 4},
  },
  intrstOuter: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: width,
    justifyContent: 'center',
    marginTop: 20,
    padding: SPACING,
  },
  customFooter: {
    backgroundColor: Color.shadedWhite,
    width: width,
    paddingHorizontal: dgl * 0.05,
    paddingVertical: dgl * 0.02,
    position: 'absolute',
    bottom: 0,
  },
  AlignCustomFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  radiostyle: {
    borderColor: Color.primaryBlue,
    borderWidth: 1,
    padding: 2,
    marginVertical: 10,
    borderRadius: 20,
  },

  MainBox: {
    flexDirection: 'row',
    backgroundColor: Color.whiteOpacity,
    borderRadius: SPACING,
    margin: SPACING,
  },
  rowBox1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomColor: Color.white,
    // width: width /,
  },
  rowBox2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: SPACING,
  },

  ColoumBox: {
    margin: SPACING,
    width: dgl * 0.38,
  },
  BoxTitle: {
    fontSize: 18,
    paddingLeft: SPACING,
    color: Color.shadedWhite,
    fontWeight: '700',
  },
  SubTitileText: {
    fontSize: dgl * 0.018,
    padding: SPACING,
    color: Color.grey,
  },
  SubDescription3: {
    fontSize: dgl * 0.014,
    padding: SPACING,
    color: Color.white,
  },
  TextBlue: {
    fontSize: dgl * 0.014,
    padding: 4,
    color: Color.primaryBlue,
    fontFamily: 'SFProDisplay-Regular',
  },
  SubTitle2: {
    fontSize: dgl * 0.011,
    padding: SPACING,
    color: Color.lightBlue,
  },
  box: {
    width: dgl * 0.2,
    height: dgl * 0.01,
    marginVertical: 20,
    borderRadius: 7.0,
    backgroundColor: '#08407E',
  },
  viewMore: {color: Color.shadedWhite, fontSize: 15},
  ProfileText: {
    fontSize: 18,
    color: Color.white,
    fontWeight: '700',
  },
  TextAlign: {textAlign: 'center'},
  ProfileSubText: {
    fontSize: 13,
    color: Color.white,
    fontWeight: '300',
  },
  //profile
  LinearProfile: {
    width: width,
    height: dgl * 0.15,
    marginTop: dgl * 0.35,
    alignItems: 'center',
    overflow: 'visible',
  },
  ProfileView: {
    width: dgl * 0.15,
    height: dgl * 0.15,
    borderRadius: dgl * 0.15,
    position: 'absolute',
    backgroundColor: '#FFFFFFD9',
    alignItems: 'center',
    bottom: dgl * 0.07,
    borderWidth: 2,
    justifyContent: 'center',
    borderColor: Color.shadedWhite,
  },
  ProfileAvatar: {
    width: dgl * 0.11,
    height: dgl * 0.11,
  },
  ProfileView2: {
    alignItems: 'center',
    marginBottom: 30,
    top: dgl * 0.09,
  },
  ProfileView3: {
    flex: 1,
    width: '100%',
  },
  viewMore1: {
    bottom: 0,
    position: 'absolute',
    justifyContent: 'space-between',
    paddingBottom: SPACING * 2,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    width: dgl * 0.1,
  },
  profileContainer: {
    borderRadius: 20,
    borderBottomWidth: 3,
    backgroundColor: Color.white,
    borderBottomColor: Color.white,
    shadowColor: Color.black,
    shadowOpacity: 0.5,
    shadowRadius: 10,
    shadowOffset: {width: -2, height: 4},
  },
  tabsView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    height: '100%',
    marginTop: 80,
    width: width - 30,
  },
  tabsView2: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  tabs: {
    flexDirection: 'row',
  },
  tab: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    width: 150,
  },
  tabLabel: {
    fontSize: 20,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  divider: {
    borderRightWidth: 1,
    borderRightColor: '#ddd',
  },
  animatedBorder: {
    height: 4,
    width: 110,
    marginTop: 4,
    backgroundColor: Color.shadedWhite,
    borderRadius: 20,
  },
  animatedBorderbg: {
    height: 5,
    width: width,
    marginTop: 4,
    backgroundColor: Color.whiteOpacity,
    borderRadius: 20,
    zIndex: 100,
    position: 'absolute',
  },
  cell: {
    flex: 1,
    padding: 10,
    borderWidth: StyleSheet.hairlineWidth,
    height: 50,
    textAlign: 'center',
    fontSize: 18,
    color: Color.shadedWhite,
    borderColor: Color.shadedWhite,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
  },
  tables: {
    borderColor: Color.shadedWhite,
    marginBottom: 10,
    marginTop: 30,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
  },
  tableContainer: {flex: 1, padding: 10, paddingTop: 30},
  border: {
    borderWidth: 1,
    borderColor: Color.whiteOpacity,
    borderTopEndRadius: 20,
  },
  head: {
    height: 40,
  },
  headText: {textAlign: 'center', fontWeight: 'bold', color: 'white'},
  cellText: {textAlign: 'center', color: 'white'},
  rows: {height: 30},
  reportHeader: {
    height: 80,
    width: width,
    flex: 0.08,
    backgroundColor: Color.white,
    top: 0,
    padding: 20,
  },
  reportHeaderAlign: {
    width: dgl * 0.03,
    height: dgl * 0.03,
    backgroundColor: Color.shadedWhite,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: dgl * 0.03,
    marginLeft: dgl * 0.02,
  },
  ReportDetails: {
    width: width - 30,
    height: height,
    justifyContent: 'center',
    backgroundColor: Color.shadedWhite,
    borderRadius: 10,
    marginTop: 20,
    overflow: 'hidden',
  },
  reportViewMoreButton: {
    alignSelf: 'center',
    width: dgl * 0.15,
    height: dgl * 0.03,
    backgroundColor: Color.shadedWhite,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: dgl * 0.15,
    shadowRadius: 10,
    shadowColor: Color.black,
    shadowOpacity: 0.23,
    shadowOffset: {width: -2, height: 4},
  },
  reportDdetailContainer: {
    flex: 4,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  reportContainerStyle: {flexDirection: 'row', justifyContent: 'space-evenly'},
  FaqContainerStyle: {
    flexDirection: 'column',
    margin: 10,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    padding: SPACING,
    shadowRadius: 10,
    shadowColor: Color.grey,
    shadowOpacity: 0.23,
    shadowOffset: {width: -2, height: 4},
    borderRadius: 10,
  },
  dropdownStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    width: '100%',
  },
  compatibilityView2: {
    width: width - 30,
    height: height / 2,
    borderRadius: SPACING,
    marginTop: SPACING,
  },
  subtextV2: {
    fontWeight: 300,
    fontSize: 13,
    // fontFamily: 'SFProDisplay-Regular',
  },
  OnBoardingParts: {
    position: 'absolute',
    bottom: SPACING * 2,
    width: width,
    padding: SPACING * 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  pushNotificationSwitch: {
    padding: SPACING,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemValue: {
    fontSize: 18,
    marginLeft: 10,
    marginVertical: 10,
  },
  weight400: {fontWeight: '400'},
  RelationShipStatusView: {
    padding: SPACING,
    flexDirection: 'row',
    width: width - 20,
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
  },
  RelationShipStatusView2: {
    flexDirection: 'row',
    width: dgl * 0.16,
  },
  radioButton: {padding: dgl * 0.008, borderRadius: 20},
  packageDetailsView: {
    height: dgl * 0.3,
    backgroundColor: Color.whiteOpacity,
    width: dgl * 0.3,
    justifyContent: 'flex-end',
    alignItems: 'center',
    borderRadius: 20,
    shadowRadius: 10,
    shadowColor: Color.grey,
    shadowOpacity: 1,
    shadowOffset: {width: -2, height: 4},
  },
  packageDetailsView2: {
    width: dgl * 0.3,
    height: dgl * 0.16,
    backgroundColor: 'blue',
    borderRadius: 20,
    borderadius: 20,
    alignItems: 'center',
  },
  packageDetailsView3: {
    height: 5,
    width: dgl * 0.2,
    borderBottomWidth: dgl * 0.005,
    borderRadius: 20,
    borderColor: Color.white,
    marginTop: 2,
  },
  packageDetailsView4: {marginTop: 20, alignItems: 'center'},
  packageBoxView1: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Color.white,
    paddingBottom: 5,
  },
  packageBoxView2: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Color.white,
    paddingBottom: 15,
  },
  currentPlanView: {
    fontSize: 16,
    color: Color.shadedBlack,
    backgroundColor: Color.whiteOpacity,
    width: dgl * 0.15,
    textAlign: 'center',
    borderRadius: dgl * 0.015,
    padding: 2,
    overflow: 'hidden',
  },
  SecondContainer: {
    width: dgl * 0.38,
    height: dgl * 0.28,
    borderRadius: 20,
    padding: 20,
    backgroundColor: Color.white,
  },
  helpDesk: {
    fontSize: 16,
    marginTop: 10,
    color: Color.shadedBlack,
  },
  helpDeskTitle: {fontSize: 20},
  dot: {
    width: 10,
    height: 10,
    backgroundColor: Color.primaryBlue,
    borderRadius: 10,
  },
  dotWhite: {
    width: 7,
    height: 7,
    backgroundColor: Color.white,
    borderRadius: 10,
  },
  dotText: {
    marginLeft: 10,
  },
  customDot: {
    color: Color.white,
    marginLeft: 10,
  },
  //make payment screeen
  ViewPlanButton: {
    width: dgl * 0.15,
    height: 45,
    borderRadius: 40,
    backgroundColor: Color.shadedWhite,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Color.white,
    justifyContent: 'center',
    alignItems: 'center',
    shadowRadius: 26,
    shadowColor: 'grey',
    shadowOpacity: 0.8,
    shadowOffset: {width: -2, height: 4},
  },
  MontlyPlanText: {
    width: dgl * 0.1,
    marginBottom: 20,
    color: Color.white,
  },
  amountText: {
    width: dgl * 0.2,
    fontSize: dgl * 0.025,
    paddingVertical: 8,
    color: Color.white,
    fontWeight: '600',
  },
  currentPlanText: {
    marginBottom: 20,
    fontWeight: '500',
    fontSize: dgl * 0.018,
    color: Color.white,
  },
  makePaymantView: {flexDirection: 'row', alignItems: 'center'},
  LinearPaymentView: {
    flex: 1,
    width: width - 30,
    height: dgl * 0.25,
    backgroundColor: 'white',
    justifyContent: 'center',
    padding: 20,
    borderRadius: 10,
    borderWidth: 5,
    borderColor: Color.primaryBlue,
  },
  outerTitle: {
    fontSize: dgl * 0.02,
    padding: 10,
    color: Color.white,
    marginTop: 20,
  },
  valueStye: {color: Color.white, fontSize: dgl * 0.018},
  valueStyeMain: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    color: Color.white,
  },
  valueText: {
    fontSize: dgl * 0.018,
    width: dgl * 0.16,
    marginLeft: dgl * 0.02,
    color: Color.white,
  },
  valueBox: {
    flex: 5,
    backgroundColor: Color.whiteOpacityL2,
    height: dgl * 0.2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Color.white,
    borderRadius: 20,
    marginBottom: 20,
  },
  DotView: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  OrderedList: {
    flex: 1,
    width: dgl * 0.3,
    backgroundColor: Color.whiteOpacityL2,
    marginBottom: 20,
    borderRadius: 10,
    padding: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Color.white,
  },
  modelOpcityBox: {
    flex: 0.45,
    width: dgl * 0.3,
    backgroundColor: Color.whiteOpacityL2,
    marginBottom: 20,
    borderRadius: 10,
  },
  modelViewAlign: {
    paddingLeft: 30,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  CloseSvgView: {
    flex: 0.1,
    width: dgl * 0.3,
    marginBottom: 20,
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginTop: 20,
  },
  subscriptionContainer: {
    flex: 0.1,
    width: dgl * 0.3,
    marginBottom: 20,
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flex4Container: {
    flex: 0.45,
    width: dgl * 0.3,
    marginBottom: 20,
    borderRadius: 10,
  },
  swtichView: {
    flex: 0.2,
    width: dgl * 0.38,
    padding: 10,
    marginBottom: 20,
    paddingHorizontal: 30,
    borderBottomWidth: 1,
    borderTopWidth: 1,
    alignItems: 'center',
    borderColor: Color.whiteOpacity,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  packagedetailsText: {fontSize: 20, fontWeight: 'bold'},
  packagedetailsText2: {flex: 6, flexDirection: 'column', marginTop: 10},
  containerStyle: {margin: 30, alignItems: 'center'},
  containerStyle2: {
    overflow: 'hidden',
    borderRadius: 20,
  },
  compatiblityView3: {
    height: dgl * 0.1,
    width: dgl * 0.1,
    backgroundColor: Color.whiteOpacity,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: dgl * 0.009,
  },
  compatiblityView4: {
    marginTop: dgl * 0.06,
    flexDirection: 'row',
    alignItems: 'center',
  },
  align: {alignItems: 'center'},
  tabView: {
    height: height / 2,
    width: width,
    padding: SPACING * 3,
  },
  GotText: {
    fontSize: 20,
    fontFamily: 'SFProDisplay-Regular',
    color: Color.primaryBlue,
  },
  gotView: {flex: 1, alignItems: 'center', width: width},
  helpContainer: {
    flex: 5,
    alignItems: 'flex-start',
    marginHorizontal: 30,
    marginTop: 30,
  },
});

export default styles;
